### ISSUE TITLE
"Trench" tiles with "Trenches" tiles

### ISSUE THREAD

**Issue by glyphloom** [Project-IS12/IS12-Warfare#38]
1. Naming is confusing. Advicing macking "trenches" tiles get name "deeptrench"
2. Their interaction is buggy. Something not right with overlay. Screenshots attached. 
(North is bad, south looks cursed)

![](https://cdn.discordapp.com/attachments/663743524885495818/763075531369218068/unknown.png)
![](https://cdn.discordapp.com/attachments/663743524885495818/763075830468837446/unknown.png)

**Comment by mattmatterson111** [comment]
That's due to how the trench overlays work. It has nothing to do with the `trenches` turf. It's not buggy, the trench overlays are just on a higher layer, so that when people enter the trench, their legs don't poke out. This means that when the trench turf borders a non dirt turf from to the south, it will have a dirty overlay.
